### ISSUE TITLE
Rename library to SpanQ

### ISSUE THREAD

**Issue by LlamaNL** [andanteyk/SpanLinq#1]
A catchy name is half the work of promotion!

original idea by: https://www.reddit.com/r/csharp/comments/1eoqibi/comment/lhfaz1g/

**Comment by JohnBaracuda** [comment]
Hey, I agree it's a catchy name, and I don't want to be the one who ruins the fun, but I prefer when libraries have clear names that show what they do. A response to a Reddit post shouldn't be the reason why a perfectly valid tool name gets changed to something less descriptive.

**Comment by andanteyk** [comment]
Thank you for the advice!
It's a bit of a hassle to change the name of a library that has already been released, and the name that directly expresses the functionality of being able to use "LINQ" with "span" is a bit simple, but I think it's not bad.
I'll keep this in mind in the future.
